name: SimpleSpigotPlugin
version: '${project.version}'
main: bonnie20402.simplespigotplugin.SimpleSpigotPlugin
api-version: 1.19
load: POSTWORLD
depend: [SlimeWorldManager]


commands:
  warp:
    aliases: [warps]
  createwarp:
    permission: "simplewarps.admin.create"
    permission-message: "You are not allowed to do this."
    aliases: [criarwarp,newwarp,setwarp]
  deletewarp:
    aliases: [delwarp,rwarp,dwarp,removewarp]
    permission: "simplewarps.admin.remove"
    permission-message: "You are not allowed to do this!"

  arena:
  test:
  setloc:
  sethome:
  home:
  guip:
  gui:
  spawn:
  setspawn:
    permission: "simplewarps.spawn.set"
  deletespawn:
    aliases: [delspawn,removespawn,rspawn,remspawn]
    permission: "simplewarps.spawn.delete"

