name: SimpleWarpPlugin
version: '${project.version}'
main: bonnie20402.simplewarpplugin.SimpleWarpPlugin
api-version: 1.19

commands:
  warp:
    aliases: [warps]
  createwarp:
    permission: "simplewarps.admin.create"
    permission-message: "You are not allowed to do this."
    aliases: [criarwarp,newwarp,setwarp]
  deletewarp:
    aliases: [delwarp,rwarp,dwarp,removewarp]
    permission: "simplewarps.admin.remove"
    permission-message: "You are not allowed to do this!"

  sethome:
  home:
  guip:
  gui:
  spawn:
  setspawn:
    permission: "simplewarps.spawn.set"
  deletespawn:
    aliases: [delspawn,removespawn,rspawn,remspawn]
    permission: "simplewarps.spawn.delete"

